version: "3.8"
services:
  postgres:
    image: postgres
    env_file: ./.env
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
  app:
    depends_on:
      - postgres
    image: maxlutovinov/web-scraping-console
    build: .
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:postgresql://postgres:$POSTGRES_DOCKER_PORT/$POSTGRES_DB",
      "spring.datasource.username" : "$POSTGRES_USER",
      "spring.datasource.password" : "$POSTGRES_PASSWORD"}'
